language: python

python:
  - 3.5
  - 3.6

notifications:
  email: false

branches:
  only:
    - master

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION ipython numpy scipy matplotlib nose pandas pip sympy pytables statsmodels numba
  - pip install coveralls coverage
  - pip install quantecon
  - python setup.py install
  - cp solowpy/tests/matplotlibrc .

script:
  - nosetests --with-coverage --cover-package=solowpy

after_success:
  - coveralls
